baseurl = "http://www.anthony-galea.com/"
languageCode = "en-us"
title = "Anthony Galea"
paginate = 42

[author]
    name = "Anthony Galea"

[permalinks]
  post = "/blog/post/:title/"

[taxonomies]
  category = "categories"

[params]
  googleAnalytics = "UA-38752250-1"
  github = "https://github.com/anthonygalea"
  twitter = "https://twitter.com/_anthonygalea"
  linkedin = "https://at.linkedin.com/in/anthonygalea"
  email = "mailto:anthony.galea@gmail.com"
  rss = true
  truncate = true
