baseurl = "https://www.anthony-galea.com/"
languageCode = "en-us"
title = "Anthony Galea"
paginate = 42
ignoreFiles = ["^\\.#"]

[author]
    name = "Anthony Galea"

[permalinks]
  post = "/blog/post/:title/"

[taxonomies]
  category = "categories"

[params]
  github = "https://github.com/anthonygalea"
  linkedin = "https://www.linkedin.com/in/anthonygalea"
  twitter = "https://twitter.com/anthonygalea"
  email = "mailto:anthony.galea@gmail.com"
  goodreads = "https://goodreads.com/anthonygalea"
  rss = true
  truncate = true
